config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'moomin', to: :moomin, controller: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def moomin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1
  Love the Booch
.carousel
  %a.carousel-item{:href => "#one!"}
    %img{:src => "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Centre_Le_Corbusier_-_%27Teich%27_-_Blatterwiese_2013-09-21_17-48-26.JPG/450px-Centre_Le_Corbusier_-_%27Teich%27_-_Blatterwiese_2013-09-21_17-48-26.JPG"}/
  %a.carousel-item{:href => "#two!"}
    %img{:src => "https://thespaces.com/wp-content/uploads/2016/12/Villa_Savoye_le-corbusier.jpg"}/
  %a.carousel-item{:href => "#three!"}
    %img{:src => "https://images.adsttc.com/media/images/55e8/90ca/46fe/9f75/3200/002c/newsletter/ronchamp-2.jpg?1441304748"}/
  %a.carousel-item{:href => "#four!"}
    %img{:src => "https://sitelecorbusier.com/wp-content/uploads/2016/08/le-corbusier-oeuvre-patrimoine-mondial-humanite-unesco-09.jpg"}/
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch
%div
  love the booch

app/views/home/moomin.html.haml
%h1
  Be a good moomin!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Sphexish
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .navbar-fixed
        %nav.blue{:role => "navigation"}
          .nav-wrapper.container
            %a#logo-container.brand-logo{:href => "#"}
              .logo.center-block
            %ul.right.hide-on-med-and-down
              %li
                = link_to 'moomin', moomin_url
              %li
                %a{:href => "#", :id => ""} Link
              %li
                %a{:href => "#", :target => "_blank"} Link
              %li
                %a{:href => "#", :target => "_blank"} Link
            %a.button-collapse{"data-activates" => "nav-mobile", :href => "#"}
              %i.material-icons menu
      %ul#nav-mobile.side-nav
        %li
          = link_to 'moomin', moomin_url
        %li
          %a{:href => "#", :id => ""} Link
        %li
          %a{:href => "#", :target => "_blank"} Link
        %li
          %a{:href => "#", :target => "_blank"} Link

    %main
      .container
        .row
          .col.s12
            / Page Content goes here
            = yield

    %footer.page-footer
      .container
        .row
          .col.l6.s12
            %h5.white-text Footer Content
            %p.grey-text.text-lighten-4 You can use rows and columns here to organize your footer content.
          .col.l4.offset-l2.s12
            %h5.white-text Links
            %ul
              %li
                %a.grey-text.text-lighten-3{:href => "#!"} Link 1
              %li
                %a.grey-text.text-lighten-3{:href => "#!"} Link 2
              %li
                %a.grey-text.text-lighten-3{:href => "#!"} Link 3
              %li
                %a.grey-text.text-lighten-3{:href => "#!"} Link 4
      .footer-copyright
        .container
          © 2014 Copyright Text
          %a.grey-text.text-lighten-4.right{:href => "#!"} More Links